# Generated by Django 4.0.4 on 2022-04-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_timestamp_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comment',
        ),
    ]
